version: '3'
services:
  grafana:
    image: grafana/grafana
    ports:
    - "3000:3000"
    volumes:
    - grafana-storage:/var/lib/grafana
volumes:
  grafana-storage: {}
  grafana-provisioning: {}

# provisioning: https://github.com/grafana/grafana/pull/10052

