name: CI

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Download dhall-to-json
      uses: Legion2/download-release-action@v2.1.0
      with:
        repository: dhall-lang/dhall-haskell
        tag: '1.27.0'
        file: dhall-json-1.5.0-x86_64-linux.tar.bz2
    - name: Build all_dashboard.dhall
      run: |
        echo "Building all_dashboard.dhall"
        ./dhall-to-json --file all_dashboard.dhall
